### ISSUE TITLE
Get started with the API docs plugin in Backstage

### ISSUE THREAD

**Issue by dhenneke** [thefrontside/backstage-openmic#1]
## Talk title 

Get started with the API docs plugin in Backstage

## Description

Use the API docs plugin to discover all your APIs in Backstage and get rendered documentations from OpenAPI, AsyncAPI, and GraphQL schemas. We show you how the plugin connects to the Backstage System model, how you can get started with the plugin, and what features you can expect from it. 

## Agenda points

- APIs and the System model of Backstage
- What is the main goal of the plugin
- Setup the plugin
- Add APIs to Backstage
- Which types of API definitions are supported
- Combine it with other plugins

**Comment by jorgelainfiesta** [comment]
Thanks @dhenneke! do you have a headshot that you'd like to share to use on the event's website? I have used your github's avatar for now

**Comment by dhenneke** [comment]
See below:

<details>
<summary>image.jpg</summary>

…

</details>
