### ISSUE TITLE
Discussion panel on representing component versions in Backstage

### ISSUE THREAD

**Issue by taras** [thefrontside/backstage-openmic#4]
## Talk title 

Understanding and gathering use case for presenting component versions

## Speaker

Taras Mankovski, CEO, The Frontside Software, Inc

## Description

I will discuss the work that our team is doing with one of our clients to bring order to versioning within their engineering organization. We will use it as a starting point for a discussion around use cases and how they can be supported in Backstage.

## Agenda points (optional)

- Briefly cover motivations for spending a lot of time thinking about versions
- Briefly cover specific considerations around different kinds of components and their versions.
- Cover some considerations based on our client's ecosystem, with the intention to get people thinking about their ecosystems.
- Gather some actionable suggestions that may become RFCs in the future

## Speaker Headshot (optional)

You have my headshots :)

**Comment by Remyapraveen** [comment]
Hi @taras, Remya here. I managed to connect the PostgreSQL parameters from Heroku-PostgreSQL to make a local deployment. But while trying to run a Dockerfile, I get this backstage_plugin_catalog' missing error. [](url)
Backend failed to start up, Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, error: no pg_hba.conf entry for host "116.15.61.141", user "ratyapoxegjukp", database "postgres", no encryption.
Have tried connecting with you through discord too.. 

![Screenshot (283)](https://user-images.githubusercontent.com/93478132/177337510-f312b5e7-3aec-4b0a-98b8-eedd3809b4d6.png)

**Comment by taras** [comment]
Let's keep this in Discord.
